<?php

use Illuminate\Database\Seeder;
use Modules\Common\Support\ImportPermissions;

return new class extends Seeder
{
    /**
     * Run the seeder.
     *
     * @return void
     */
    public function run(): void
    {
        $menus = $this->menus();

        ImportPermissions::import($menus);
    }

    public function menus(): array
    {
        return array (
  0 => 
  array (
    'id' => 37,
    'parent_id' => 0,
    'permission_name' => '系统管理',
    'route' => '/system',
    'icon' => 'server-stack',
    'module' => 'system',
    'permission_mark' => '',
    'component' => '/layout/index.vue',
    'redirect' => '',
    'keepalive' => 1,
    'type' => 1,
    'hidden' => 1,
    'sort' => 1,
    'active_menu' => '',
    'creator_id' => 1,
    'created_at' => '2024-05-10 18:10',
    'updated_at' => '2024-05-10 18:10',
    'children' => 
    array (
      0 => 
      array (
        'id' => 38,
        'parent_id' => 37,
        'permission_name' => '字典管理',
        'route' => 'dictionary',
        'icon' => '',
        'module' => 'system',
        'permission_mark' => 'dictionary',
        'component' => '/system/dictionary/index.vue',
        'redirect' => '',
        'keepalive' => 1,
        'type' => 2,
        'hidden' => 1,
        'sort' => 1,
        'active_menu' => '',
        'creator_id' => 1,
        'created_at' => '2024-05-10 18:10',
        'updated_at' => '2024-05-10 18:10',
        'children' => 
        array (
          0 => 
          array (
            'id' => 39,
            'parent_id' => 38,
            'permission_name' => '删除',
            'route' => '',
            'icon' => '',
            'module' => 'system',
            'permission_mark' => 'dictionary@destroy',
            'component' => '',
            'redirect' => '',
            'keepalive' => 1,
            'type' => 3,
            'hidden' => 1,
            'sort' => 5,
            'active_menu' => '',
            'creator_id' => 1,
            'created_at' => '2024-05-10 18:10',
            'updated_at' => '2024-05-10 18:10',
          ),
          1 => 
          array (
            'id' => 40,
            'parent_id' => 38,
            'permission_name' => '禁用/启用',
            'route' => '',
            'icon' => '',
            'module' => 'system',
            'permission_mark' => 'dictionary@enable',
            'component' => '',
            'redirect' => '',
            'keepalive' => 1,
            'type' => 3,
            'hidden' => 1,
            'sort' => 6,
            'active_menu' => '',
            'creator_id' => 1,
            'created_at' => '2024-05-10 18:10',
            'updated_at' => '2024-05-10 18:10',
          ),
          2 => 
          array (
            'id' => 41,
            'parent_id' => 38,
            'permission_name' => '列表',
            'route' => '',
            'icon' => '',
            'module' => 'system',
            'permission_mark' => 'dictionary@index',
            'component' => '',
            'redirect' => '',
            'keepalive' => 1,
            'type' => 3,
            'hidden' => 1,
            'sort' => 1,
            'active_menu' => '',
            'creator_id' => 1,
            'created_at' => '2024-05-10 18:10',
            'updated_at' => '2024-05-10 18:10',
          ),
          3 => 
          array (
            'id' => 42,
            'parent_id' => 38,
            'permission_name' => '读取',
            'route' => '',
            'icon' => '',
            'module' => 'system',
            'permission_mark' => 'dictionary@show',
            'component' => '',
            'redirect' => '',
            'keepalive' => 1,
            'type' => 3,
            'hidden' => 1,
            'sort' => 3,
            'active_menu' => '',
            'creator_id' => 1,
            'created_at' => '2024-05-10 18:10',
            'updated_at' => '2024-05-10 18:10',
          ),
          4 => 
          array (
            'id' => 43,
            'parent_id' => 38,
            'permission_name' => '新增',
            'route' => '',
            'icon' => '',
            'module' => 'system',
            'permission_mark' => 'dictionary@store',
            'component' => '',
            'redirect' => '',
            'keepalive' => 1,
            'type' => 3,
            'hidden' => 1,
            'sort' => 2,
            'active_menu' => '',
            'creator_id' => 1,
            'created_at' => '2024-05-10 18:10',
            'updated_at' => '2024-05-10 18:10',
          ),
          5 => 
          array (
            'id' => 44,
            'parent_id' => 38,
            'permission_name' => '更新',
            'route' => '',
            'icon' => '',
            'module' => 'system',
            'permission_mark' => 'dictionary@update',
            'component' => '',
            'redirect' => '',
            'keepalive' => 1,
            'type' => 3,
            'hidden' => 1,
            'sort' => 4,
            'active_menu' => '',
            'creator_id' => 1,
            'created_at' => '2024-05-10 18:10',
            'updated_at' => '2024-05-10 18:10',
          ),
        ),
      ),
      1 => 
      array (
        'id' => 45,
        'parent_id' => 37,
        'permission_name' => '字典值管理',
        'route' => 'dictionary/values/:id',
        'icon' => '',
        'module' => 'system',
        'permission_mark' => 'dictionaryValues',
        'component' => '/system/dictionaryValues/index.vue',
        'redirect' => '',
        'keepalive' => 1,
        'type' => 2,
        'hidden' => 2,
        'sort' => 1,
        'active_menu' => '/system/dictionary',
        'creator_id' => 1,
        'created_at' => '2024-05-10 18:10',
        'updated_at' => '2024-05-10 18:10',
        'children' => 
        array (
          0 => 
          array (
            'id' => 46,
            'parent_id' => 45,
            'permission_name' => '删除',
            'route' => '',
            'icon' => '',
            'module' => 'system',
            'permission_mark' => 'dictionaryValues@destroy',
            'component' => '',
            'redirect' => '',
            'keepalive' => 1,
            'type' => 3,
            'hidden' => 2,
            'sort' => 5,
            'active_menu' => '',
            'creator_id' => 1,
            'created_at' => '2024-05-10 18:10',
            'updated_at' => '2024-05-10 18:10',
          ),
          1 => 
          array (
            'id' => 47,
            'parent_id' => 45,
            'permission_name' => '禁用/启用',
            'route' => '',
            'icon' => '',
            'module' => 'system',
            'permission_mark' => 'dictionaryValues@enable',
            'component' => '',
            'redirect' => '',
            'keepalive' => 1,
            'type' => 3,
            'hidden' => 2,
            'sort' => 6,
            'active_menu' => '',
            'creator_id' => 1,
            'created_at' => '2024-05-10 18:10',
            'updated_at' => '2024-05-10 18:10',
          ),
          2 => 
          array (
            'id' => 48,
            'parent_id' => 45,
            'permission_name' => '列表',
            'route' => '',
            'icon' => '',
            'module' => 'system',
            'permission_mark' => 'dictionaryValues@index',
            'component' => '',
            'redirect' => '',
            'keepalive' => 1,
            'type' => 3,
            'hidden' => 2,
            'sort' => 1,
            'active_menu' => '',
            'creator_id' => 1,
            'created_at' => '2024-05-10 18:10',
            'updated_at' => '2024-05-10 18:10',
          ),
          3 => 
          array (
            'id' => 49,
            'parent_id' => 45,
            'permission_name' => '读取',
            'route' => '',
            'icon' => '',
            'module' => 'system',
            'permission_mark' => 'dictionaryValues@show',
            'component' => '',
            'redirect' => '',
            'keepalive' => 1,
            'type' => 3,
            'hidden' => 2,
            'sort' => 3,
            'active_menu' => '',
            'creator_id' => 1,
            'created_at' => '2024-05-10 18:10',
            'updated_at' => '2024-05-10 18:10',
          ),
          4 => 
          array (
            'id' => 50,
            'parent_id' => 45,
            'permission_name' => '新增',
            'route' => '',
            'icon' => '',
            'module' => 'system',
            'permission_mark' => 'dictionaryValues@store',
            'component' => '',
            'redirect' => '',
            'keepalive' => 1,
            'type' => 3,
            'hidden' => 2,
            'sort' => 2,
            'active_menu' => '',
            'creator_id' => 1,
            'created_at' => '2024-05-10 18:10',
            'updated_at' => '2024-05-10 18:10',
          ),
          5 => 
          array (
            'id' => 51,
            'parent_id' => 45,
            'permission_name' => '更新',
            'route' => '',
            'icon' => '',
            'module' => 'system',
            'permission_mark' => 'dictionaryValues@update',
            'component' => '',
            'redirect' => '',
            'keepalive' => 1,
            'type' => 3,
            'hidden' => 2,
            'sort' => 4,
            'active_menu' => '',
            'creator_id' => 1,
            'created_at' => '2024-05-10 18:10',
            'updated_at' => '2024-05-10 18:10',
          ),
        ),
      ),
      2 => 
      array (
        'id' => 58,
        'parent_id' => 37,
        'permission_name' => '附件管理',
        'route' => 'systemAttachments',
        'icon' => '',
        'module' => 'system',
        'permission_mark' => 'systemAttachments',
        'component' => '/system/systemAttachments/index.vue',
        'redirect' => '',
        'keepalive' => 1,
        'type' => 2,
        'hidden' => 2,
        'sort' => 1,
        'active_menu' => '',
        'creator_id' => 1,
        'created_at' => '2024-05-10 18:10',
        'updated_at' => '2025-12-04 04:08',
        'children' => 
        array (
          0 => 
          array (
            'id' => 59,
            'parent_id' => 58,
            'permission_name' => '删除',
            'route' => '',
            'icon' => '',
            'module' => 'system',
            'permission_mark' => 'systemAttachments@destroy',
            'component' => '',
            'redirect' => '',
            'keepalive' => 1,
            'type' => 3,
            'hidden' => 2,
            'sort' => 2,
            'active_menu' => '',
            'creator_id' => 1,
            'created_at' => '2024-05-10 18:10',
            'updated_at' => '2024-05-10 18:10',
          ),
          1 => 
          array (
            'id' => 60,
            'parent_id' => 58,
            'permission_name' => '列表',
            'route' => '',
            'icon' => '',
            'module' => 'system',
            'permission_mark' => 'systemAttachments@index',
            'component' => '',
            'redirect' => '',
            'keepalive' => 1,
            'type' => 3,
            'hidden' => 2,
            'sort' => 1,
            'active_menu' => '',
            'creator_id' => 1,
            'created_at' => '2024-05-10 18:10',
            'updated_at' => '2024-05-10 18:10',
          ),
        ),
      ),
      3 => 
      array (
        'id' => 55,
        'parent_id' => 37,
        'permission_name' => '上传配置',
        'route' => 'upload/config',
        'icon' => '',
        'module' => 'system',
        'permission_mark' => 'uploadConfig',
        'component' => '/system/uploadConfig/index.vue',
        'redirect' => '',
        'keepalive' => 1,
        'type' => 2,
        'hidden' => 1,
        'sort' => 1,
        'active_menu' => '',
        'creator_id' => 1,
        'created_at' => '2024-05-10 18:10',
        'updated_at' => '2025-12-04 04:08',
        'children' => 
        array (
          0 => 
          array (
            'id' => 56,
            'parent_id' => 55,
            'permission_name' => '删除',
            'route' => '',
            'icon' => '',
            'module' => 'system',
            'permission_mark' => 'systemConfig@destroy',
            'component' => '',
            'redirect' => '',
            'keepalive' => 1,
            'type' => 3,
            'hidden' => 1,
            'sort' => 2,
            'active_menu' => '',
            'creator_id' => 1,
            'created_at' => '2024-05-10 18:10',
            'updated_at' => '2024-05-10 18:10',
          ),
          1 => 
          array (
            'id' => 57,
            'parent_id' => 55,
            'permission_name' => '列表',
            'route' => '',
            'icon' => '',
            'module' => 'system',
            'permission_mark' => 'systemConfig@index',
            'component' => '',
            'redirect' => '',
            'keepalive' => 1,
            'type' => 3,
            'hidden' => 1,
            'sort' => 1,
            'active_menu' => '',
            'creator_id' => 1,
            'created_at' => '2024-05-10 18:10',
            'updated_at' => '2024-05-10 18:10',
          ),
        ),
      ),
    ),
  ),
);
    }
};
