<?php 
// This file is automatically generated at:2019-11-29 08:20:23
declare (strict_types = 1);
return array (
  'module\\index\\IndexService' => false,
  'module\\install\\InstallService' => false,
  'module\\login\\LoginService' => false,
  'module\\permissions\\PermissionService' => false,
  'module\\user\\UserService' => false,
);