<?php
// +----------------------------------------------------------------------
// | CatchAdmin [Just Like ～ ]
// +----------------------------------------------------------------------
// | Copyright (c) 2017~2020 http://catchadmin.com All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( https://github.com/yanwenwu/catch-admin/blob/master/LICENSE.txt )
// +----------------------------------------------------------------------
// | Author: JaguarJack [ njphper@gmail.com ]
// +----------------------------------------------------------------------
namespace catchAdmin\wechat\repository;

use catchAdmin\wechat\model\WechatReply;
use catcher\base\CatchRepository;

class WechatReplyRepository extends CatchRepository
{
    protected $reply;

    public function __construct(WechatReply $reply)
    {
        $this->reply = $reply;
    }

    public function model()
    {
        return $this->reply;
    }

    public function storeBy(array $data)
    {
        return parent::storeBy($data); // TODO: Change the autogenerated stub
    }
}