<?php

namespace Modules\User\Providers;

use Catch\CatchAdmin;
use Catch\Providers\CatchModuleServiceProvider;
use Modules\User\Events\Login;
use Modules\User\Listeners\Login as LoginListener;

class UserServiceProvider extends CatchModuleServiceProvider
{
    protected array $events = [
        Login::class => LoginListener::class
    ];

    /**
     * route path
     *
     * @return string|array
     */
    public function routePath(): string|array
    {
        // TODO: Implement path() method.
        return CatchAdmin::getModuleRoutePath('user');
    }


    public function registerEvents(array $events): void
    {
        parent::registerEvents($events); // TODO: Change the autogenerated stub
    }
}
